### ISSUE TITLE
Configurar Docker

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Grupo1#12]
### Descrição

Configurar docker para execução dos projetos em desenvolvimento e em ambiente de produção.

### Tasks

- [ ] Configurar docker para desenvolvimento - backend
- [ ] Configurar docker para produção - backend
- [ ] Configurar docker para desenvolvimento - frontend
- [ ] Configurar docker para produção - frontend

**Comment by thiagorpereira** [comment]
Foi utilizado o guia [Quickstart: Compose and Rails](https://docs.docker.com/compose/rails/) para a dockerização base do Rails, variando um pouco na inicialização, utilizando o [Rails API-only](https://guides.rubyonrails.org/api_app.html); 

Material complementar: https://onebitcode.com/api-completa-rails/

**Comment by thiagorpereira** [comment]
Já para a dockerização do React e o Build de 2 imagens (Dockerfile) em pastas distintas, a maior referencia utilizada foi: [Creating an app with Docker Compose, Django, and Create React App](https://dev.to/englishcraig/creating-an-app-with-docker-compose-django-and-create-react-app-31lf), primeiramente foi iniciado utilizando [Create React App](https://create-react-app.dev/docs/getting-started) e enfim a solução da dockerização foi sendo adaptada com as nossas respectivas tecnologias

**Comment by thiagorpereira** [comment]
PR submetido; @kairon-v já q vc conhece substancialmente das stacks, confere o PR #20 ?
